name: "Upload Quest"
description: "Upload new draft for a quest in Wilco"
inputs:
  quest-editor-user-email:
    description: "Quest editor email"
    required: true
  quest-editor-user-token:
    description: "Quest editor unique token"
    required: true
  wilco-engine-url:
    description: "URL of the Wilco Engine URL"
    required: false
    default: "https://engine.wilco.gg"
runs:
  using: 'node16'
  main: 'dist/index.js'
