name: "Upload Quest"
description: "Upload new draft for a quest in Wilco"
inputs:
  quest-editor-user-email:
    description: "Quest editor email"
    required: true
  quest-editor-user-token:
    description: "Quest editor unique token"
    required: true
  wilco-engine-url:
    description: "URL of the Wilco Engine URL"
    required: false
    default: "https://engine.wilco.gg"
runs:
  using: "composite"
  steps:
    - id: zip-quest-info
      run: zip -r quest.zip .
      shell: bash
    - name: Set quest id
      id: get_id
      run: echo quest_id=`cat quest.yml | grep "^id:" | awk '{ print $2}' | sed "s/['\"]//g"` >> $GITHUB_OUTPUT
      shell: bash
    - name: curl
      uses: wei/curl@master
      with:
        args: "-V"
