name: "Upload Quest"
description: "Upload new draft for a quest in Wilco"
inputs:
  quest-editor-user-email:
    description: "Quest editor email"
    required: true
  quest-editor-user-token:
    description: "Quest editor unique token"
    required: true
  wilco-engine-url:
    description: "URL of the Wilco Engine URL"
    required: false
    default: "https://engine.wilco.gg"
runs:
  using: "composite"
  steps:
    - id: zip-quest-info
      run: zip -r quest.zip .
      shell: bash
    - id: upload-draft
      run: |
        curl --request PUT --url "${{ inputs.wilco-engine-url }}/api/v1/editor/quest/$( cat quest.yml | grep "^id:" | awk '{ print $2}' | sed "s/['\"]//g" )?isPrimaryId=true" -H "x-editor-user-token: ${{ inputs.quest-editor-user-token }}" -H "x-editor-user-email: ${{ inputs.quest-editor-user-email }}" -F "file=@quest.zip;type=application/x-zip-compressed" --fail-with
      shell: bash
